version: '3'

networks:
  frontend:
    external: true

services:
  web:
    build:
      context: ../
      dockerfile: docker/dockerfile
    image: c4h-frontend
    container_name: c4h-frontend
    volumes:
      - ../:/web:cached
    ports:
      - "8888:8888"
    command:
      - yarn
      - start:dev
    networks:
      - frontend
     
